spring.application.name=api_rate_limiter

# use redis backed storage
# spring.profiles.active=redis

# use in-memory storage
spring.profiles.active=memory

spring.data.redis.host=localhost
spring.data.redis.port=6379